version: '2.1'

services:
    frontend:
        image: node:alpine
        entrypoint: ./frontend-entry.sh
        volumes:
            - ./frontend/:/frontend/
            - ./frontend-entry.sh:/frontend-entry.sh

    proxy:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        links:
            - frontend
        ports:
            - 80:80
