version: '2.1'

services:
    api:
        image: node:alpine
#       entrypoint: ./api-entry.sh
        environment:
            - API_ROUTE_PREFIX=/api
            - PORT=5000
            - JWT_KEY=${JWT_KEY}
            - MONGO_ADMIN_PASSWORD=${MONGO_ADMIN_PASSWORD}
        volumes:
            - ./api/:/api/
            - ./api-entry.sh:/api-entry.sh
            - ./data/images/:/api/images/
            - ./wait-for/wait-for:/usr/bin/wait-for
        links:
            - database
        command: sh -c 'wait-for database:27017 -- npm run --prefix /api dev'
#       depends_on:
#           database:
#               condition: service_healthy

    frontend:
        image: node:alpine
        entrypoint: ./frontend-entry.sh
        volumes:
            - ./frontend/:/frontend/
            - ./frontend-entry.sh:/frontend-entry.sh

    proxy:
        image: nginx:alpine
        volumes:
            - ./data/images/:/www/images/
            - ./nginx.conf:/etc/nginx/nginx.conf
        links:
            - frontend
            - mongoexpress
            - api
            - swaggereditor
        ports:
            - 80:80

    database:
#       image: mongo:latest
        build: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_USERNAME=admin
            - MONGO_PASSWORD=${MONGO_ADMIN_PASSWORD}
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db/:/data/db/
#           - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
#           - ./mongo/docker-entrypoint.sh:/tmp/docker-entrypoint.sh
#       entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
#       command: bash -c "cp /tmp/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh; chown root:root /usr/local/bin/docker-entrypoint.sh; mongod --auth"
#        command: mongod --auth
#       healthcheck:
#           test: "exit 0"

    mongoexpress:
#       image: mongo-express
        build: mongo-express
        links:
            - database
        environment:
            - ME_CONFIG_MONGODB_SERVER=database
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_SITE_BASEURL=/mongoadmin/
        volumes:
            - ./wait-for/wait-for:/usr/bin/wait-for
              # Very rude hack :O
            - ./nc:/usr/bin/nc
        command: /bin/sh -c 'wait-for database:27017 -- node /app/node_modules/.bin/cross-env NODE_ENV=production node app'
#       command: cat /docker-entrypoint.sh
#       depends_on:
#           database:
#               condition: service_healthy

    swaggereditor:
        image: swaggerapi/swagger-editor
        ports:
            - 8080:8080

# vim: et ts=4 sw=4 :
